apiVersion: apps/v1
kind: Deployment
metadata:
  name: openresty
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openresty
  template:
    metadata:
      labels:
        name: openresty
    spec:
      containers:
        - name: openresty
          image: registry.cn-hangzhou.aliyuncs.com/limingmax/ai:v6
          env:
          - name: REDIS_IP
            value: "192.168.193.1"
          - name: REDIS_PORT
            value: "30098"
          ports:
          - containerPort: 8899
          command: ['/bin/bash', '/etc/openresty-mq/up.sh']

---
apiVersion: v1
kind: Service
metadata:
  name: openresty
  namespace: ai
  labels:
    name: openresty
spec:
  type: NodePort
  ports:
  - port: 8899
    protocol: TCP
    targetPort: 8899
    name: http
    nodePort: 32318
  selector:
    name: openresty
